version: '3'

volumes:
    production_postgres_data: { }
    production_postgres_data_backups: { }
    production_traefik: { }

services:
    django: &django
        image: lucascluk/shiritori:django-latest
        depends_on:
            - postgres
            - redis
        env_file:
            - backend/.envs/.production/.django
            - backend/.envs/.production/.postgres
        command: /start

    postgres:
        image: lucascluk/shiritori:psql-latest
        volumes:
            - production_postgres_data:/var/lib/postgresql/data
            - production_postgres_data_backups:/backups
        env_file:
            - backend/.envs/.production/.postgres

    traefik:
        image: lucascluk/shiritori:traefik-latest
        depends_on:
            - django
            - nuxt
        volumes:
            - production_traefik:/etc/traefik/acme
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            - "0.0.0.0:5555:5555"

    redis:
        image: redis:6

    celeryworker:
        <<: *django
        image: lucascluk/shiritori:celery-latest
        command: /start-celeryworker

    celerybeat:
        <<: *django
        image: lucascluk/shiritori:celery-beat-latest
        command: /start-celerybeat

    nuxt:
        image:
            lucascluk/shiritori:nuxt-latest
