name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1
    DJANGO_SETTINGS_MODULE: "config.settings.test"

on:
    pull_request:
        branches: [ "master", "main" ]

    push:
        branches: [ "master", "main" ]

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:

            -   name: Checkout Code Repository
                uses: actions/checkout@v3

            -   name: Install poetry
                run: |
                    curl -O -sSL https://install.python-poetry.org/install-poetry.py
                    python install-poetry.py -y --version 1.4.0
                    echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
                    rm install-poetry.py

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: "3.11"
                    cache: "poetry"
                    cache-dependency-path: "backend/pyproject.toml"
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip poetry ruff
                    cd backend
                    poetry install
            -   name: Ruff
                run: |
                    ruff check $(git ls-files '*.py')
            -   name: Black
                run: |
                    cd backend
                    poetry run black --check $(git ls-files '*.py')
            -   name: Isort
                run: |
                    cd backend
                    poetry run isort --check-only --profile black $(git ls-files '*.py')
    #            -   name: Mypy TODO: Fix mypy errors
    #                run: |
    #                    cd backend
    #                    poetry run mypy $(git ls-files '*.py')

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Code Repository
                uses: actions/checkout@v3

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: "3.11"
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip poetry
                    cd backend
                    poetry install --with production
            -   name: Run DB Migrations
                run: |
                    cd backend
                    poetry run python manage.py migrate
            -   name: Run Django Tests
                run: |
                    cd backend
                    poetry run pytest
